version: '3.0'
services:
    crawler_ptt:
        build:  # 定義如何構建 Docker 映像。
            context: ./  # 指定 Dockerfile 所在的上下文路徑，這裡是當前目錄。
            dockerfile: Dockerfile  # 指定用於構建映像的 Dockerfile 名稱。
        image: crawl-worker
        # volumes:
        #     - '.:/opt/crawl'
        # 先把hostname註解掉，因為我們才可以用一台instance建立多個worker，因為hostname是唯一性
        # hostname: "ptt-worker"
        # 在docker compose複雜的command指令需要用以下方式寫，此方式可以建立多個不同hostname的worker，超好用
        command: ["sh", "-c", "export MY_HOSTNAME=ptt-worker-`hostname` && echo Setting hostname to $$MY_HOSTNAME && pipenv run celery -A financialdata.tasks.worker worker --loglevel=info --concurrency=1 --hostname=$$MY_HOSTNAME -Q pttCrawler"]
        restart: always
        environment:
          - TZ=Asia/Taipei
        networks:
            - dev

networks:
  dev: