version: '3.0'
services:
  ptt-scheduler:
    image: crawl-worker
    hostname: "ptt-scheduler"
    command: pipenv run python financialdata/tasks/scheduler.py
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
        - dev

networks:
  dev:
